In [2]:
import pandas as pd
import numpy as np
import calendar
from pathlib import Path

# Cleaning the raw data we get from NHS A&E attendance

In [3]:
# Generate list of month names (January to December)
months = list(calendar.month_name)[1:]

# Define year range (2018–2025 inclusive)
years = list(range(2018, 2026))

# Read Excel file:
# - skip first 14 rows (metadata/headers not needed)
# - header is multi-level (2 rows)
# - select specific sheet
def process_file(year, month):  
    try:
        df_prov = pd.read_excel(
            f'./Datasets/Raw/{year}/{month}.xls',
            skiprows=14,
            header=[0, 1],
            sheet_name='Provider Level Data'
        )
    except Exception as e:
        print(f"Error reading {year}-{month}: {e}")

    # Remove first and last columns (usually empty or totals not needed)
    df_prov = df_prov.iloc[:, 1:-1]


    # Flatten multi-level column headers:
    # - remove 'Unnamed' columns (artifacts from Excel merged cells)
    # - clean spaces and unwanted characters
    # - join levels using '_'
    df_prov.columns = [
        '_'.join([
            str(lvl).strip()
            .replace('Unnamed:', '')
            .replace(' - ', '_')
            .strip('_ ')
            for lvl in col
            if pd.notna(lvl) and 'Unnamed' not in str(lvl)
        ])
        for col in df_prov.columns
    ]


    # Drop columns containing percentage values (not required for analysis)
    df_prov = df_prov.loc[:, ~df_prov.columns.str.contains('Percentage')]


    # Add metadata columns for tracking
    df_prov['Month'] = month
    df_prov['Year'] = year


    # Rename columns to a consistent schema:
    # This ensures all files align structurally for downstream analysis
    new_cols = [
        'Code', 'Region', 'Name',
        'Attend_Type1', 'Attend_Type2', 'Attend_Type3', 'Attend_Total',
        'Within4Hr_Type1', 'Within4Hr_Type2', 'Within4Hr_Type3', 'Within4Hr_Total',
        'Over4Hr_Type1', 'Over4Hr_Type2', 'Over4Hr_Type3', 'Over4Hr_Total',
        'Adm_AE_Type1', 'Adm_AE_Type2', 'Adm_AE_Type3', 'Adm_AE_Total',
        'Adm_Other', 'Adm_Total',
        'DecisionToAdm_Wait_4to12Hr', 'DecisionToAdm_Wait_Over12Hr',
        'Month', 'Year'
    ]

    if len(df_prov.columns) != len(new_cols):
        print(f"Column mismatch in {year}-{month}")
        return None
    
    df_prov.columns = new_cols


    # Remove rows with any missing values (missing code data)
    # (ensures clean dataset for analysis)
    df_prov = df_prov.dropna()


    # Remove invalid rows where provider code is '-'
    # (these are usually summary or placeholder rows)
    df_prov = df_prov[df_prov['Code'] != '-'].reset_index(drop=True)

    return df_prov

## Merging dataframes and creating and exporting final dataset

In [4]:
### creating 1 final file
all_data = []

for year in years:
    for month in months:
        df = process_file(year, month)
        if df is not None:
            all_data.append(df)

# Combine all into one DataFrame
final_df = pd.concat(all_data, ignore_index=True)

## Data preprocessing and EDA

In [5]:
final_df.head()

,Code,Region,Name,Attend_Type1,Attend_Type2,Attend_Type3,Attend_Total,Within4Hr_Type1,Within4Hr_Type2,Within4Hr_Type3,...,Adm_AE_Type1,Adm_AE_Type2,Adm_AE_Type3,Adm_AE_Total,Adm_Other,Adm_Total,DecisionToAdm_Wait_4to12Hr,DecisionToAdm_Wait_Over12Hr,Month,Year
0,RF4,London Commissioning Region,"Barking, Havering And Redbridge University Hos...",21317.0,813.0,3040.0,25170.0,15213.0,813.0,2953.0,...,4988.0,0.0,0.0,4988.0,62.0,5050.0,128.0,0.0,January,2018
1,R1H,London Commissioning Region,Barts Health NHS Trust,27281.0,770.0,15910.0,43961.0,21442.0,770.0,15827.0,...,7738.0,0.0,0.0,7738.0,1853.0,9591.0,1721.0,0.0,January,2018
2,AD913,London Commissioning Region,Beckenham Beacon Ucc,0.0,0.0,4574.0,4574.0,0.0,0.0,4574.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,January,2018
3,E84069,London Commissioning Region,Belmont Health Centre,0.0,0.0,1891.0,1891.0,0.0,0.0,1891.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,January,2018
4,Y02692,London Commissioning Region,Brent GP Access Unit Harness-Wembley,0.0,0.0,4217.0,4217.0,0.0,0.0,4217.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,January,2018

In [6]:
final_df=final_df.replace('-',0)

C:\Users\guruchela\AppData\Local\Temp\ipykernel_9064\4035264394.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df=final_df.replace('-',0)

In [7]:
#exporting final df into csv
final_df.to_csv('./Datasets/Cleaned/master_dataset.csv', index=False)

In [11]:
final_df['Attend_Type1'].iloc[6412]

np.float64(5045.0)

In [14]:
final_df

,Code,Region,Name,Attend_Type1,Attend_Type2,Attend_Type3,Attend_Total,Within4Hr_Type1,Within4Hr_Type2,Within4Hr_Type3,...,Adm_AE_Type1,Adm_AE_Type2,Adm_AE_Type3,Adm_AE_Total,Adm_Other,Adm_Total,DecisionToAdm_Wait_4to12Hr,DecisionToAdm_Wait_Over12Hr,Month,Year
0,RF4,London Commissioning Region,"Barking, Havering And Redbridge University Hos...",21317.0,813.0,3040.0,25170.0,15213.0,813.0,2953.0,...,4988.0,0.0,0.0,4988.0,62.0,5050.0,128.0,0.0,January,2018
1,R1H,London Commissioning Region,Barts Health NHS Trust,27281.0,770.0,15910.0,43961.0,21442.0,770.0,15827.0,...,7738.0,0.0,0.0,7738.0,1853.0,9591.0,1721.0,0.0,January,2018
2,AD913,London Commissioning Region,Beckenham Beacon Ucc,0.0,0.0,4574.0,4574.0,0.0,0.0,4574.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,January,2018
3,E84069,London Commissioning Region,Belmont Health Centre,0.0,0.0,1891.0,1891.0,0.0,0.0,1891.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,January,2018
4,Y02692,London Commissioning Region,Brent GP Access Unit Harness-Wembley,0.0,0.0,4217.0,4217.0,0.0,0.0,4217.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,January,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20541,RA9,NHS England South West,Torbay And South Devon NHS Foundation Trust,7021.0,0.0,3174.0,10195.0,4046.0,0.0,3171.0,...,2222.0,0.0,0.0,2222.0,1147.0,3369.0,211.0,56.0,December,2025
20542,G3P9C,NHS England South West,Trowbridge Minor Injuries Unit,0.0,0.0,993.0,993.0,0.0,0.0,992.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,December,2025
20543,RA7,NHS England South West,University Hospitals Bristol And Weston NHS Fo...,16151.0,2167.0,0.0,18318.0,10195.0,1998.0,0.0,...,5082.0,11.0,0.0,5093.0,1620.0,6713.0,1715.0,496.0,December,2025
20544,R0D,NHS England South West,University Hospitals Dorset NHS Foundation Trust,14438.0,0.0,4035.0,18473.0,8140.0,0.0,4035.0,...,4387.0,1.0,0.0,4388.0,2396.0,6784.0,1490.0,395.0,December,2025
20545,RK9,NHS England South West,University Hospitals Plymouth NHS Trust,8876.0,96.0,7009.0,15981.0,3819.0,89.0,6943.0,...,3148.0,0.0,0.0,3148.0,1819.0,4967.0,1129.0,441.0,December,2025